extensions:
  topgg: # If your discord bpt is on top.gg, you can enable this extension to post your stats (server count, shard count, etc.) on top.gg automatically.
    enabled: false
    token: "top.gg token here" # https://docs.top.gg/docs/API/@reference/#authentication
  ping:
    enabled: true
bot:
    token: "bot token here" # Your bot token
