[tool.poetry]
name = "botkit"
version = "0.1.0"
description = ""
authors = ["NiceBots.xyz <hello@nicebots.xyz>"]
readme = "README.md"
license = "MIT"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
py-cord = "^2.5.0"
aiohttp = "^3.9.5"
pyyaml = "^6.0.1"
python-dotenv = "^1.0.1"
orjson = "^3.10.3"


[tool.poetry.group.dev.dependencies]
black = "^24.4.2"

[tool.poetry.scripts]
start = "main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
