name: CI/CD

on:
  push:
    branches: [ "main", "dev" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "dev" ]

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  docker:
    needs: tests
    uses: ./.github/workflows/docker.yaml
    secrets: inherit